version: '2'
services:
  web:
    build: .
    command: bash start.sh
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - database:docker_mysql
  
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: s0m3p455
      MYSQL_DATABASE: app_development
      MYSQL_USER: root
      MYSQL_PASSWORD: s0m3p455
