version: "3"

services:
  database:
    container_name: database
    image: postgres:12-alpine
    ports: [ "5432:5432" ]
    networks: [ raw_net ]
    env_file: [ ".env" ]
    logging:
      driver: "none"

  app:
    image: app:latest
    container_name: app
    build: .
    command: sh scripts/start
    volumes: [ ".:/app", ".app_data/gems:/.app_data/gems" ]
    ports: [ "3000:3000" ]
    networks: [ raw_net ]
    env_file: [ ".env" ]
    links: [ database ]
    depends_on: [ database ]

volumes:
  .app_data:

networks:
  raw_net:
    driver: bridge