version: '2'
services:
  app:
    build: .
    command: bash -c "
      cd web &&
      rm tmp/* -Rf &&
      rails new . &&
      rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
    volumes:
      - $APP_PATH_PROJECT:/app/web
    ports:
      - "3111:3000"
    depends_on:
      - database
    links:
      - database:docker_mysql
  database:
    image: mysql:5.7
    ports:
      - "3371:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
